name: LeetCode-collectinator

on: 
  #schedule : 
   # - cron : '*/5 * * * *' # your favourable timing
   
  workflow_dispatch :

jobs : 
  build :
    runs-on : ubuntu-latest 

    steps : 
      - name: Checking out
        uses: actions/checkout@v2
      
      - name : show file contents
        run :  |
            ls -a
      - name : Using LC-Collectinator
        uses: ME-ON1/Leetcode-SyncInAction@ffdc94f82be2f77caf7a5c577978e6ab9bbb5ea7
        with :
           cookieVal : ${{ secrets.COOKIE_SECRET }} # secrets.cookieVal coming from repository secret    
           solution_location : /All-Solutions  # if any , default is root '.'

       # dependency, to write newly created files to the root directory of the repository.  

      - name: pushing the changes!!
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
           commit_message: Adding new LC solutions # or anything you want to add.
